language: r
warnings_are_errors: true
sudo: required
cache: packages

addons:
  apt:
    packages:
      - r-cran-rjava
      - udunits-bin
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libgdal1-dev
      - libudunits2-dev

before_install:
  - cd r-package
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'
