language: r

warnings_are_errors: true

sudo: required

cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - r-cran-rjava
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libudunits2-dev

before_install:
  - sudo $(which R) CMD javareconf
  - cd r-package
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

after_success:
 - Rscript -e 'covr::codecov()'
