jdk:
  - openjdk11


matrix:
  include:
    - language: r
      warnings_are_errors: true
      sudo: required
      cache: packages
    - jdk: openjdk11
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"


      r_packages:
       - devtools

      r_github_packages:
        - r-lib/covr

      before_install:
       - ./.travis/install_java_11.0.5
       - cd r-package
       - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
       - sudo apt-get --yes --force-yes update -qq
       - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev
       - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

      after_success:
       - Rscript -e 'covr::codecov()'
