language: r
warnings_are_errors: true
sudo: false
cache: packages

r_packages:
 - devtools

r_github_packages:
  - r-lib/covr

jdk: openjdk11
script:
  - jdk_switcher use openjdk11
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME

before_install:
 - cd r-package
 - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
 - sudo apt-get --yes --force-yes update -qq
 - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

after_success:
 - Rscript -e 'covr::codecov()'
